
# TAREAS
###

POST http://localhost:8500/api/tareas HTTP/1.1
Content-Type: application/json

{

"tarea": "comer",
"descripcion": "comprar comida ",
"estado": "false"
}


###
GET http://localhost:8500/api/tareas HTTP/1.1


###

GET http://localhost:8500/api/tareas/63e523540f8f8f449ca16013 HTTP/1.1

###

PUT http://localhost:8500/api/tareas/63ed0aa139c0e85259d11e9b HTTP/1.1
Content-Type: application/json

{

"tarea": "Jugar",
"descripcion": "Jugar Play",
"estado": "true"
}

###

DELETE http://localhost:8500/api/tareas/63e523540f8f8f449ca16013  HTTP/1.1